version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34.10
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-107-21-93-51.compute-1.amazonaws.com
            port: '5432'
            database: d8tg0odnc0o833
            ssl: true
            user: qtoovlxwvdbiak
            password: f0001fd16532f5792c33ed3c8242472af324c0b87baca948bfcd68bc9f917f44
            migrations: true